In [2]:
import pandas as pd
import numpy as np
print(f"Pandas version: {pd.__version__}")
print(f"NumPy version: {np.__version__}")

Pandas version: 3.0.3
NumPy version: 2.4.6

In [5]:
df = pd.read_csv("archive/Combined_dataset.csv")
print(f"Dataset loaded: {df.shape[0]} rows × {df.shape[1]} columns")

Dataset loaded: 1000 rows × 24 columns

In [6]:
#2.Data Exploration

In [7]:
# Displaying first 5 rows
print("FIRST 5 ROWS")
df.head()

FIRST 5 ROWS

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
0,8376765,Lino Perros,Women Navy Blue Solid Backpack,3.8,15,3995,58.0,"""₹3,995.00""",INR,http://assets.myntassets.com/assets/images/837...,...,"{""1_star"":2,""2_stars"":0,""3_stars"":3,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""rw-8376765_cae700""]",NaN,[{}],{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
1,9136281,Tommy Hilfiger,Unisex Navy Blue Striped Backpack,4.5,67,2899,35.0,"""₹2,899.00""",INR,http://assets.myntassets.com/assets/images/913...,...,"{""1_star"":3,""2_stars"":4,""3_stars"":2,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""rw-9136281_cae700""]",NaN,"[{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
2,17633752,Lavie,Aries Women Pink Mini Backpack,4.4,226,2999,65.0,"""₹2,999.00""",INR,http://assets.myntassets.com/assets/images/176...,...,"{""1_star"":9,""2_stars"":5,""3_stars"":10,""4_stars""...",NaN,NaN,"[{""size"":""S""}]","[""https://videos.myntassets.com/assets/videos/...",NaN,"[{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
3,1376949,F Gear,Unisex Navy & Grey Printed Burner Backpack,4.4,1052,1675,52.0,"""₹1,675.00""",INR,http://assets.myntassets.com/assets/images/137...,...,"{""1_star"":33,""2_stars"":21,""3_stars"":69,""4_star...",NaN,NaN,"[{""size"":""Onesize""}]","[""https://videos.myntassets.com/assets/videos/...",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
4,13939916,MYTRIDENT,Men Blue Solid Bath Robe,4.7,12,2899,17.0,"""₹2,899.00""",INR,http://assets.myntassets.com/assets/images/pro...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""M"",""value"":""45.0in"",""value_name"":""Fr...",NaN,NaN,"[{},{},{},{},{},{},{},{},{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on IndusI...",bath-robe

In [8]:
# Displaying last 5 rows
print("LAST 5 ROWS")
df.tail()

LAST 5 ROWS

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
995,13698258,KREDO,Men FORTE Silver Automatic Skeleton Analogue W...,3.5,11,11890,50.0,"""₹11,890.00""",INR,http://assets.myntassets.com/assets/images/136...,...,"{""1_star"":3,""2_stars"":0,""3_stars"":2,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""pi-13698258""]",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches
996,16896006,GUESS,Women White Patterned Dial & White Straps Anal...,5.0,22,8900,45.0,"""₹8,900.00""",INR,http://assets.myntassets.com/assets/images/168...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""rw-16896006_cae700"",""https://videos.myntasse...",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches
997,1708108,GIORDANO,Women Rose Gold-Toned Mirrored Analogue Watch ...,2.8,5,7950,50.0,"""₹7,950.00""",INR,http://assets.myntassets.com/assets/images/170...,...,"{""1_star"":2,""2_stars"":1,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]",NaN,NaN,"[{},{},{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches
998,19280114,Fastrack,Men Black Brass Dial & Black Stainless Steel S...,4.3,17,3295,20.0,"""₹2,636.00""",INR,http://assets.myntassets.com/assets/images/192...,...,"{""1_star"":1,""2_stars"":2,""3_stars"":0,""4_stars"":...",NaN,Tru███m R███il,"[{""size"":""Onesize""}]",NaN,Sho███o. ███-10█████████enu███████████████████...,NaN,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",watches
999,18601682,BOLDFIT,Purple Textured Yoga Mat,3.8,161,699,31.0,"""₹699.00""",INR,http://assets.myntassets.com/assets/images/186...,...,"{""1_star"":24,""2_stars"":8,""3_stars"":22,""4_stars...",NaN,NaN,"[{""size"":""Medium""}]",NaN,NaN,"[{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",yoga-mats

In [11]:
#Shape ,rows,colums
print("Shape:", df.shape)
print("Columns:", df.columns)

Shape: (1000, 24)
Columns: Index(['product_id', 'title', 'product_description', 'rating', 'ratings_count',
       'initial_price', 'discount', 'final_price', 'currency', 'images',
       'delivery_options', 'product_details', 'breadcrumbs',
       'product_specifications', 'amount_of_stars', 'what_customers_said',
       'seller_name', 'sizes', 'videos', 'seller_information', 'variations',
       'best_offer', 'more_offers', 'category'],
      dtype='str')

In [12]:
#Displaying data types
print("\nData Types:")
print(df.dtypes)

Data Types:
product_id                  int64
title                         str
product_description           str
rating                    float64
ratings_count               int64
initial_price               int64
discount                  float64
final_price                   str
currency                      str
images                        str
delivery_options              str
product_details               str
breadcrumbs                   str
product_specifications        str
amount_of_stars               str
what_customers_said           str
seller_name                   str
sizes                         str
videos                        str
seller_information            str
variations                    str
best_offer                    str
more_offers                   str
category                      str
dtype: object

In [13]:

#3:Handling Missing Values

In [14]:
#Identifying missing values
print("Missing values per column")
print(df.isnull().sum())
print()
print(f"Total missing values in dataset: {df.isnull().sum().sum()}")

Missing values per column
product_id                  0
title                       0
product_description         0
rating                      0
ratings_count               0
initial_price               0
discount                  121
final_price                 0
currency                    0
images                      0
delivery_options            0
product_details             0
breadcrumbs                 0
product_specifications      0
amount_of_stars             0
what_customers_said       573
seller_name               301
sizes                       0
videos                    781
seller_information        301
variations                562
best_offer                  0
more_offers                 0
category                    0
dtype: int64

Total missing values in dataset: 2639

In [15]:
#Filling missing values
#Numeric columns with median value
for col in df.select_dtypes(include='number').columns:
    df[col] = df[col].fillna(df[col].median())
    print(f"Filled numeric column '{col}' with median")

#Text/object columns with "Unknown"
for col in df.select_dtypes(include='object').columns:
    df[col] = df[col].fillna('Unknown')
    print(f"Filled text column '{col}' with 'Unknown'")

Filled numeric column 'product_id' with median
Filled numeric column 'rating' with median
Filled numeric column 'ratings_count' with median
Filled numeric column 'initial_price' with median
Filled numeric column 'discount' with median
Filled text column 'title' with 'Unknown'
Filled text column 'product_description' with 'Unknown'
Filled text column 'final_price' with 'Unknown'
Filled text column 'currency' with 'Unknown'
Filled text column 'images' with 'Unknown'
Filled text column 'delivery_options' with 'Unknown'
Filled text column 'product_details' with 'Unknown'
Filled text column 'breadcrumbs' with 'Unknown'
Filled text column 'product_specifications' with 'Unknown'
Filled text column 'amount_of_stars' with 'Unknown'
Filled text column 'what_customers_said' with 'Unknown'
Filled text column 'seller_name' with 'Unknown'
Filled text column 'sizes' with 'Unknown'
Filled text column 'videos' with 'Unknown'
Filled text column 'seller_information' with 'Unknown'
Filled text column 'variations' with 'Unknown'
Filled text column 'best_offer' with 'Unknown'
Filled text column 'more_offers' with 'Unknown'
Filled text column 'category' with 'Unknown'

C:\Users\Admin\AppData\Local\Temp\ipykernel_8440\1854115945.py:8: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  for col in df.select_dtypes(include='object').columns:

In [19]:
#Droping the rows containg missing values
df.dropna(inplace=True)

In [20]:
#Verifying if missing values are remaining
print(f"Missing values remaining: {df.isnull().sum().sum()}")
print("No missing values found")

Missing values remaining: 0
No missing values found

In [21]:
#4 BASIC OPERATIONS

In [24]:
#Filtering rows
#Check column names
print(df.columns.tolist())

['product_id', 'title', 'product_description', 'rating', 'ratings_count', 'initial_price', 'discount', 'final_price', 'currency', 'images', 'delivery_options', 'product_details', 'breadcrumbs', 'product_specifications', 'amount_of_stars', 'what_customers_said', 'seller_name', 'sizes', 'videos', 'seller_information', 'variations', 'best_offer', 'more_offers', 'category']

In [27]:
# Filtering products with rating more than 4
filtered = df[df['rating'] > 4]
print("High rated products : {len(filtered)}")
filtered.head()

High rated products : {len(filtered)}

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
1,9136281,Tommy Hilfiger,Unisex Navy Blue Striped Backpack,4.5,67,2899,35.0,"""₹2,899.00""",INR,http://assets.myntassets.com/assets/images/913...,...,"{""1_star"":3,""2_stars"":4,""3_stars"":2,""4_stars"":...",Unknown,Unknown,"[{""size"":""Onesize""}]","[""rw-9136281_cae700""]",Unknown,"[{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
2,17633752,Lavie,Aries Women Pink Mini Backpack,4.4,226,2999,65.0,"""₹2,999.00""",INR,http://assets.myntassets.com/assets/images/176...,...,"{""1_star"":9,""2_stars"":5,""3_stars"":10,""4_stars""...",Unknown,Unknown,"[{""size"":""S""}]","[""https://videos.myntassets.com/assets/videos/...",Unknown,"[{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
3,1376949,F Gear,Unisex Navy & Grey Printed Burner Backpack,4.4,1052,1675,52.0,"""₹1,675.00""",INR,http://assets.myntassets.com/assets/images/137...,...,"{""1_star"":33,""2_stars"":21,""3_stars"":69,""4_star...",Unknown,Unknown,"[{""size"":""Onesize""}]","[""https://videos.myntassets.com/assets/videos/...",Unknown,Unknown,{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
4,13939916,MYTRIDENT,Men Blue Solid Bath Robe,4.7,12,2899,17.0,"""₹2,899.00""",INR,http://assets.myntassets.com/assets/images/pro...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",Unknown,Unknown,"[{""size"":""M"",""value"":""45.0in"",""value_name"":""Fr...",Unknown,Unknown,"[{},{},{},{},{},{},{},{},{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on IndusI...",bath-robe
5,17198778,H&M,Beige & Tan Solid Stoneware Soap Dispenser,4.5,42,1399,56.0,"""₹1,399.00""",INR,http://assets.myntassets.com/assets/images/171...,...,"{""1_star"":2,""2_stars"":2,""3_stars"":0,""4_stars"":...",Unknown,H &███Hen███ & █████████eta█████████████████████,"[{""size"":""Onesize""}]",Unknown,Pra███yat███fra█████████PVT███████████████████...,"[{},{}]","{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",bathroom-accessories

In [31]:
#Select columns
#Selecing few important columns
selected = df[['title', 'category', 'rating', 'final_price']]
print("Shape : {selected.shape}")
selected.head()

Shape : {selected.shape}

            title   category  rating  final_price
0     Lino Perros  backpacks     3.8  "₹3,995.00"
1  Tommy Hilfiger  backpacks     4.5  "₹2,899.00"
2           Lavie  backpacks     4.4  "₹2,999.00"
3          F Gear  backpacks     4.4  "₹1,675.00"
4       MYTRIDENT  bath-robe     4.7  "₹2,899.00"

In [32]:
#5. Removing duplicates

In [35]:
#Removing duplicates
df.drop_duplicates(inplace=True)

In [36]:
# Counting duplicates
print("Duplicate Rows:", df.duplicated().sum())

Duplicate Rows: 0

In [37]:
#CREATING DERIVED COLUMNS

In [38]:
# Adding a quantity column
df['quantity'] = 1
# Creating total_amount column
df['total_amount'] = df['final_price'] * df['quantity']
# Verifying
print("total_amount COLUMN CREATED")
print(df[['title', 'initial_price', 'discount', 'final_price', 'quantity', 'total_amount']].head(10))
print()
print("Max total amount  : {df['total_amount'].max()}")
print("Min total amount  : {df['total_amount'].min()}")
print("Mean total amount : {df['total_amount'].mean():.2f}")
print("Derived column created!")

total_amount COLUMN CREATED
            title  initial_price  discount  final_price  quantity total_amount
0     Lino Perros           3995      58.0  "₹3,995.00"         1  "₹3,995.00"
1  Tommy Hilfiger           2899      35.0  "₹2,899.00"         1  "₹2,899.00"
2           Lavie           2999      65.0  "₹2,999.00"         1  "₹2,999.00"
3          F Gear           1675      52.0  "₹1,675.00"         1  "₹1,675.00"
4       MYTRIDENT           2899      17.0  "₹2,899.00"         1  "₹2,899.00"
5             H&M           1399      56.0  "₹1,399.00"         1  "₹1,399.00"
6      AVI Living           1399      65.0  "₹1,399.00"         1  "₹1,399.00"
7         My Room           2999      54.0  "₹2,999.00"         1  "₹2,999.00"
8         My Room           2999      54.0  "₹2,999.00"         1  "₹2,999.00"
9      Story@home           2199      53.0  "₹2,199.00"         1  "₹2,199.00"

Max total amount  : {df['total_amount'].max()}
Min total amount  : {df['total_amount'].min()}
Mean total amount : {df['total_amount'].mean():.2f}
Derived column created!

In [39]:
#Saving the cleaned dataset
df.to_csv("shopping_cleaned.csv", index=False)

In [40]:
#Verification
print(f"File name   : shopping_cleaned.csv")
print(f"Final shape : {df.shape[0]} rows × {df.shape[1]} columns")

File name   : shopping_cleaned.csv
Final shape : 1000 rows × 26 columns

In [41]:
#Quantity and total_amount columns were added